CSIS-iLab/new-silk-road

DETAILED_INSTRUCTIONS.md
Adding some additional notes on getting the project running on Ubuntu.
Note: This merges these changes into the staging branch. Going forward, I think we plan on using `staging` and `master` as the two primary long lived branches.
=> [RA-2] Ubuntu Docs

DETAILED_INSTRUCTIONS.md
Added a couple of notes about setting up the project locally.
=> [RA-1] Mac Developer Setup Docs

DETAILED_INSTRUCTIONS.md, README.md, dev-requirements.txt
https://caktus.atlassian.net/browse/RA-3
To run local tests, I had to:
- upgrade `factory-boy` (see the [factory-boy ImportError](https://github.com/FactoryBoy/factory_boy/issues/334))
- run `elasticsearch`
I've also added to the documentation about how to run tests locally.
=> [Ra-3] Local Tests

.travis.yml, dev-requirements.txt, search/tests/test_searches.py, setup.cfg, writings/tests/factories.py, writings/tests/test_models.py
Enabling Travis CI to run the tests and track coverage.
=> [RA-9] Travis Setup

.travis.yml
:crossed_fingers: This works to help us track coverage improvements and potential regressions.
=> Adding Codecov Support

DETAILED_INSTRUCTIONS.md
This assumes access to the Heroku team.
=> [RA-18] Add instructions for getting DB snapshots from staging/production

finance/tests/test_currency.py, setup.cfg
https://caktus.atlassian.net/browse/RA-24
This pull request adds 1 test for the 1 function in `finance`.
=> [RA-24] Improve Test Coverage For Finance Section

.travis.yml
Configures Travis CI to auto deploy staging to the Heroku staging site. It will also run the migrations and restart the app. This is using my encrypted Heroku token. It would need to be rotated if my access was dropped from the Heroku team.
=> [RA-37] Heroku Deploy

website/templates/base.html
Reverts CSIS-iLab/new-silk-road#162
=> Revert "Glaring change which will be reverted shortly; testing continuous dep…"

README.md, docs/upgrading_django.md
https://caktus.atlassian.net/browse/RA-34
This pull request adds documentation for recommendations on how to do Django upgrades.
=> [RA-34] Documentation for Django Upgrades

requirements.txt
Follow up from #166. Needs to be tested/confirmed on staging before moving this forward.
=> [HOTFIX] Upgrade django-rq

.travis.yml, DETAILED_INSTRUCTIONS.md, HEROKU.md, Procfile
Adding documentation on the services used on Heroku. Also setup the migrations to run automatically on deploy in the Procfile rather than through Travis CI. Let me know if there is anything that I missed or should expand on.
=> [RA-36] Heroku Docs

sources/apps.py, sources/models.py, sources/tests.py, sources/views.py
Pretty small module. Mostly removing files which aren't needed. Updated the `str` logic to handle null values for `original_filename` since you can't return `None` from `__str__`.
=> [RA-30] Sources Tests

.travis.yml, HEROKU.md, requirements.txt
This changes adds
- Auto deployment to production on push/merge to master
- Fixes issues with collectstatic re-copying unchanged files due to timezones
- Email notifications on deploy
=> [RA-35] Deploy Automation

api/filters/facts.py, api/filters/infrastructure.py, api/filters/locations.py, api/serializers/locations.py, api/views.py, newsilkroad/settings.py, requirements.txt
https://caktus.atlassian.net/browse/TRH-2935
This pull request upgrades `django_rest_framework` to version `3.8.2` (the newest release), as well as upgrading relevant dependencies (`django-filter` has been upgraded from `0.15.2` to `1.1.0`, and `djangorestframework-filters` has been upgraded from `0.9.0` to `0.10.2`).
There has been more work on `django-filter` to make a `2.0` release, but it is not quite ready yet (only `2.0.0.dev1` has been released, and it has breaking changes with `djangorestframework-filters`, which is also planning a `1.0` release, but is also not ready for that. I tried to make a few changes that will make these upgrades easier in the future, when the major version releases are made.
=> [TRH-2935] Upgrade DRF And Related Libraries

infrastructure/forms.py
Project funding in the admin was still crashing in the admin as part of TRH-2957.
=> Correct a missing model assignment for select2 widgets

infrastructure/admin.py, infrastructure/forms.py, requirements.txt
Fixes to improve the speed of the project edit pages in the admin.
=> Production Release

facts/admin/organizations.py, facts/forms.py, infrastructure/forms.py
Refactor a few slow rendering fields on the organization form to improve page load time.
=> [TRH-3055] Organization Form Speed

facts/admin/organizations.py
TRH-3055 take two from @jbradberry. There are likely other places on the site which could use a similar change/optimization.
=> [TRH-3055] Preselect related objects for Document str/repr

infrastructure/forms.py, infrastructure/tests/test_forms.py
After adding the `PowerPlant` model in #203, editing `PowerPlant`s in the admin had the bug that users were not able to add or remove `Project`s. This pull request fixes the bug.
=> PowerPlantForm Can Save Projects

infrastructure/admin.py
Added some filter option and detail data to show up in:
- Owner Stake Admin
- Fuel Admin
- Fuel Categories Admin
=> Admin Enhancement

DETAILED_INSTRUCTIONS.md
This pull request makes a few changes to the developer setup instructions:
- The `elasticsearch` version is now specified
- The way to create a search index is mentioned in the docs
=> Improve Developer Setup Documentation

infrastructure/forms.py, locations/admin.py, locations/forms.py, locations/tests/test_forms.py
This pull request fixes some of the admin timeouts related to the power plant import.
=> Fix Admin Timeouts

newsilkroad/settings.py, website/urls.py
Remove duplicated logic and update existing code to allow testing on bravo.
=> Enable toolbar based on user

api/tests.py, api/views.py, powerplants.ipynb
Remove projects with multiple power plants
=> Limit power plant projects on map

.travis.yml, README.md
* Disable automated Heroku deployment for now (not currently working)
* Build every branch
=> Fix CI test runner

infrastructure/forms.py
Adds a modification to the admin label for `linear_length`.
=> Adds custom label to project form

infrastructure/templates/infrastructure/initiative_detail.html
Adds a check in the template to make sure that a related project is published before displaying it.
=> [RA-150] Fixes unpublished projects in initiative detail

DETAILED_INSTRUCTIONS.md, README.md
A couple of additions to the README and DETAILED_INSTRUCTIONS of things that I needed to finish getting on board with this project.
=> Onboarding sah

sources/admin.py
This PR addresses a bug that was noticed while researching another ticket RA-153.  The fix was easy enough as it came out during the research process so I went ahead and added this PR even though RA-153 was closed as a non-issue.
See Jira for notes on how to reproduce.
=> [RA-154] Fixes search fields for admin form

infrastructure/tests/test_views.py, search/tests/test_serializers.py, search/tests/test_tasks.py, search/tests/test_views.py, setup.cfg, website/tests/test_views.py, website/urls.py, website/views.py
Redirects the main views for database and maps.
Skips tests that relied on these active views.
=> Ra 163 redirect urls
