setup.cfg
https://caktus.atlassian.net/browse/RA-27
I didn't find anything in the `newsilkroad` directory worth testing, so I omitted it from coverage.
=> [RA-27] Omit newsilkroad From Test Coverage

requirements.txt
This is currently failing to run in production with `error: unrecognized arguments: default`. This is an incompatibility with Django 1.10 and was fixed in 0.9.4. Once this has been tested on staging I'll merge into master and fix on production.
=> Need to upgrade django-rq to get the arg parsing fix

.travis.yml
TravisCI did not link the format of the changes adding the production deployment in #169. See https://travis-ci.org/CSIS-iLab/new-silk-road/builds/257749249. I've broken these out into two sections as recommended here https://stackoverflow.com/questions/39506192/travis-ci-deploy-different-branches-to-different-servers. `travis lint` no longer shows errors on the deploy section with this change.
=> Fixing Deploy Errors Related to RA-35

writings/admin.py, writings/apps.py, writings/templates/writings/entry_detail.html, writings/tests/factories.py, writings/tests/test_admin.py, writings/tests/test_models.py, writings/tests/test_views.py, writings/views.py
Testing for the `writings` app. Excluded a few branches from coverage which shouldn't execute while running the site. There are there to catch developer errors/misconfigurations.
=> [RA-33] Writings Tests

api/filters/infrastructure.py
https://caktus.atlassian.net/browse/TRH-2935
The work in #181 missed a few `RelatedFilter`s that need to have a `queryset` defined. This pull request defines them.
=> [TRH-2935] Upgrade DRF And Related Libraries Part 2

api/filters/infrastructure.py, api/tests.py
The update of `djangorestframework-filters` broke the `/api/organizations/?principal_initiatives__isnull=False` filter used by the map for populating the options for filtering. I tried using `lookups='__all__'` as described by the docs but it wasn't working so I worked around it instead.
=> [TRH-2954] Fix Organziation Filtering

facts/admin/people.py, facts/forms.py, infrastructure/admin.py, locations/forms.py, newsilkroad/settings.py
These require explicit model or queryset values to work on the most recent version.
=> [TRH-2957] Updating select2 widgets

infrastructure/forms.py
https://caktus.atlassian.net/browse/TRH-2966
This error was happening when the admin user tried to save a `ProjectFunding` instance without a `Project` in the admin. Looking at the models, `ProjectFunding` requires a relationship to a `Project`, and the 1297 `ProjectFunding` instances in the database all contain a relationship to a `Project`. The fix here is to make `ProjectFundingForm.project` a required field. Since this form is only used in one place, it doesn’t seem like it will have unintended consequences.
=> [TRH-2966] Saving Project Funding In Admin

infrastructure/admin.py, infrastructure/forms.py
The project detail pages in the admin take a long time to render. That's due largely to the long select boxes for the M2M fields. Converting most of these (particularly the organization lookups) greatly improves the page load time.
=> [TRH-3030] Improve Project Page Render Time

infrastructure/forms.py
`search_fields` needs to be declared on the widget rather than the field.
=> [TRH-3030] Fix to how the organizational search is declared

facts/admin/organizations.py
Previously the organization admin search looked across many/all related objects for the search phrase. This resulted in a very expense query across more than a dozen tables. This has instead been focused on the common case which is searching for organizations by name.
=> [TRH-3054] Organization Admin Search

requirements.txt
This pull request upgrades Django from `1.11.12` to `1.11.15`, mainly to take advantage of the [most recently Django security patch](https://docs.djangoproject.com/en/2.1/releases/1.11.15/) that fixes a vulnerability for sites that use `settings.APPEND_SLASH` to automatically add a `/` to the end of URLs.
=> Upgrade To Django 1.11.15

infrastructure/templates/infrastructure/project_detail.html
This pull request updates the project detail page, so that the description is now just below the title for projects that are power plants. The detail page should continue to look the same for other projects.
=> Update Project Detail Page

locations/admin.py, power_plant_import/import_csv_to_database.py, power_plant_import/tests/test_import_to_database.py
This pull request makes the following updates to the power plant import (originally merged in in #204):
- each `Project`’s latitude and longitude have been switched (they were being imported backwards previously)
=> Update Power Plant Import

infrastructure/admin.py, infrastructure/forms.py
This pull request fixes an admin timeout on the `PowerPlant` admin detail page:
- the `geo` options now load using a `GeometrySearchField`, like on the `Project` admin detail page
- the `ProjectsOwnersInline` now has a raw id field for `owner`, instead of loading each of the `Organization`s as an `<option>` in the DOM
=> Fix PowerPlant Admin Timeout

api/views.py
* do not cache PP API calls so cache can be enabled which select2 requires
* Adjust the following env vars in the heroku dashboard as well:
```
DISABLE_CACHE = False
SELECT2_CACHE_BACKEND = default
```
=> admin select2 errors

DETAILED_INSTRUCTIONS.md, docker-compose.yml
Add Docker containers for running production-matching versions of PostgreSQL, Elasticsearch, etc. for local development testing.
=> Add docker support for auxiliary services

infrastructure/admin.py, newsilkroad/settings.py, requirements.txt
After some initial testing (documented in RA-44), this PR moves the select2 cache to its own cache location, freeing it from potentially being clobbered in the primary cache. This is still a hunch, but here's what this attempts to fix:
* The site is heavily cached and always hovers around the max cache memory (100mb)
* django-select2 caches requests when the admin page loads
* On the production site, which is active, requests continue to be served/cached as users navigate the site
* Memcache runs out of memory, uses the LRU eviction process, and happens to purge the block of memory that select2 used
* select2 starts failing with a "key not found" error
By using a separate cache, this hopes to avoid that problem.
This is currently set to merge into the **master** branch, since this may be …
=> Allow moving select2 to a different cache location

infrastructure/admin.py, infrastructure/forms.py, sources/forms.py
/admin/infrastructure/projectdocument/add/ failed to load on production because it was trying to render a 2k+ ``select`` field. To mimic the rest of the site, this PR implements a select2-style autocomplete for the Document model and adds it to the ProjectDocument admin.
Some other notes:
* The ProjectDocument admin list view generated a lot of SQL queries, so I added ``select_related`` and ``prefetch_related`` to reduce the number on page load
* I added ``sources/forms.py`` rather than ``sources/fields.py`` to mimic the project setup elsewhere
=> Fix ProjectDocument admin loading issue

docker-compose.yml, infrastructure/templates/infrastructure/powerplant_detail.html, infrastructure/templates/infrastructure/project_detail.html, infrastructure/views.py
Modifies the template for Powerplants to display the category.  I looks like users of the site have been adding this information in as parentheses.  So until they change that it may look a little strange.
I added some styling to the template to add columns and labels so it is clearer what the data is.
=> [RA-49] Display fuel category alongside fuel type on user-facing detail pages

package.json
Weirdly enough:
- Updating this requirement does not induce any changes in the bundled JS that need to be committed
- It seems the result we were hoping for from upgrading this, namely map labels working on Firefox, is already there on staging
My guess is that although I *did* revert the changes to the repo that took place during my too-hasty push of the upgraded Mapbox GL code earlier, I did *not* restore a pre-upgrade state of `node_modules` locally after doing that, meaning that I was accidentally committing code that included the upgraded bundle whenever I committed the latest changes.
The upside is that there is basically nothing to verify in this PR. The bundles have not been changed, therefore the code is actually the same; this is just ratifying the existing state of the bundle by …
=> Update mapbox-gl requirement

newsilkroad/settings.py
This PR gets the CACHE_MIDDLEWARE_SECONDS setting from the environment if available.
To set this variable on staging, you have to do something like:
```
$ heroku config:set CACHE_MIDDLEWARE_SECONDS=1 --app csis-reconasia-bravo
```
This has already been done.
=> [ra-125] get cache timeout from the environment if available

website/assets/sass/_searchview.scss
To see the problem, look at the map and hover your cursor in the space to the right of one of the infra type icons. You'll see it light up. Click it: you'll see it grey out & see the map update.
This is because the use of `transform` rather than some "real" position property results in the elements that have been moved out of view *not actually* being moved, simply being visually shifted; so they're still there and still clickable.
The easiest solution is to ensure that their overall container resizes appropriately on hover / non-hover so that they're not clickable when not in their hover state. To do this, we can use the old `max-width` transition trick (which emulates transitioning between `width: auto` and some known width).
=> Fix bad sizing of infrastructure type toggle container

website/assets/sass/_pages.scss, website/assets/sass/main.scss
Removes the left align on related blocks table data. The left align made the layout conflict with client wireframes.
=> [RA-151] Revert to previous layout

infrastructure/models.py, infrastructure/templates/infrastructure/project_detail.html
After Neil’s excellent review on the original version of this ticket and talking with Gerald, we came to the conclusion that the cases we had set out for this were a little confusing and a little contradictory.
There seems to be no need to worry about decimal place if a number were to get as large as 1 million 1,000,000.78 seems to be a ludicrous precision on such a large number (we are not talking nuclear physics here).
So the best course of actions appears to be to allow values over 1 million to be humanized. I was wrong about the behavior of humanize; it appears that humanize does work on float values even though it’s code says it passes non-integers right through :shrug:), and values lower than one million to retain their decimals even though 999,999.78 is just as ludicrous a …
=> Ra 156 humanize values
